### ISSUE TITLE
是否能增加只针对目录改名功能？

### ISSUE THREAD

**Issue by dextersa** [ccf-2012/torcp#11]
在 --move-run 模式下，
对已经命名或者标注的媒体文件夹增加--emby-bracket 的时候，  还是会改变文件夹里的一些内容或者有一些文件夹内的文件不会被移走，这样有时候会造成一些麻烦，比如poster，角色歌等内容等会被遗留，所以希望增加仅对目录改名的功能。
在处理剧集或者动画片的时候很有必要。

**Comment by ccf-2012** [comment]
#d4b72b22

修改`-e` 参数，允许使用 `-e all` 使得所有文件都相应处理。
相应处理的意思是：
- 如果使用`--origin-name` 参数，则原文件名过去
- 如果没有，则改为片名及后缀过去

当前尚未发到pip上，供源码使用测试，即使用 [这里所述的方法](https://github.com/ccf-2012/torcp#%E4%BD%BF%E7%94%A8%E6%BA%90%E7%A0%81%E8%B0%83%E7%94%A8%E7%9A%84%E6%96%B9%E5%BC%8F)
