### ISSUE TITLE
希望加个参数，不创建movie文件夹

### ISSUE THREAD

**Issue by brucmao** [ccf-2012/torcp#2]
`python3 /Y/torcp/torcp.py "/Y/src/All-Time Box Office World-wide" --hd_pat=/Y/dst/TOP50/ --movie`

网上下载了top50的电影合集
这个会创建文件夹  /Y/dst/TOP50/Movie ，最后这个Movie 文件夹多余，希望可以有参数设置取消

**Comment by ccf-2012** [comment]
在脚本运行完后，移动一整个目录，以及改名，应当是很简单的事了，也应当在本脚本之外运行
